name: coveralls

on: ["push", "pull_request"]

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Use Node.js 14.15.0
      uses: actions/setup-node@v3
      with:
        node-version: 14.15.0

    - name: npm install, make test-coverage
      run: |
        npm ci
        npm run test:coveralls
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}