on: 
  push: 
    branches: [ feature-14-coveralls ]

on: 
  pull_request: 
    branches: [ feature-14-coveralls ]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Use Node.js 14.x
      uses: actions/setup-node@master
      with:
        node-version: 14.x

    - name: npm install, make test-coverage
      run: |
        npm ci
        make test-coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      env:
        NODE_COVERALLS_DEBUG: 1
      with:
        github-token: ${{ secrets.REPO_TOKEN }}
