on: ["push", "pull_request"]

name: Test Coveralls

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Use Node.js 14.x
      uses: actions/setup-node@master
      with:
        node-version: 14.x

    - name: npm install, make test-coverage
      run: |
        npm i
        npm run-script test-coverage
    - name: Coveralls
      uses: coverallsapp/github-action@master
      env:
        NODE_COVERALLS_DEBUG: 1
        COVERALLS_SERVICE_NAME: 'GitHub CI'
        COVERALLS_GIT_BRANCH: feature-14-coveralls
        COVERALLS_REPO_TOKEN : ${{ secrets.REPO_TOKEN }}
      with:
        github-token: ${{ secrets.REPO_TOKEN }}